export type KnowledgeArticle = {
  id: string
  title: string
  category: string
  summary: string
  purpose: string
  steps: string[]
  tips: string[]
  related?: string[]
  updated: string
}

export const CUSTOMER_KNOWLEDGE: KnowledgeArticle[] = [
  {
    id: "start-here",
    title: "Start Here: Your First 15 Minutes with Lux Agent",
    category: "Getting Started",
    summary: "The fastest path from install to a useful first result.",
    purpose: "Use this when Lux Agent is installed and you want to know what to do first.",
    steps: [
      "Open Lux Agent Desktop and complete the basic business profile.",
      "Meet LANA and tell her what your business does, who you serve, and your main goal.",
      "Open Build My Lux or Success Packs and choose the closest profession pack.",
      "Add optional Memory Packs only if they help your work.",
      "Ask LANA for a 7-day action plan and review it before anything is sent or published.",
    ],
    tips: ["Keep your first setup simple.", "You can add more packs later.", "LANA is included automatically."],
    related: ["build-my-lux", "success-packs", "lana"],
    updated: "2026-10-01",
  },
  {
    id: "build-my-lux",
    title: "Build My Lux: The 5-Step Setup Guide",
    category: "Getting Started",
    summary: "Choose a Success Pack, add Memory, choose your team, choose install target, then review.",
    purpose: "Use this if you want a guided setup instead of configuring Lux manually.",
    steps: [
      "Step 1: Choose the Success Pack closest to your profession or business.",
      "Step 2: Add optional Memory Packs for deeper knowledge.",
      "Step 3: Keep the standard professional team or choose Premium Team Customization.",
      "Step 4: Choose Desktop, USB, or both.",
      "Step 5: Review the setup, complete checkout, and install the signed Lux setup.",
    ],
    tips: ["Success Pack first; Memory second.", "Custom agents are optional.", "The standard team is enough for most customers."],
    related: ["success-packs", "memory-packs", "installing-lux"],
    updated: "2026-10-01",
  },
  {
    id: "success-packs",
    title: "What Is a Success Pack?",
    category: "Success Packs",
    summary: "Success Packs are prebuilt, profession-specific AI team setups.",
    purpose: "Use this to understand why Success Packs are the recommended starting point.",
    steps: [
      "Choose the pack that most closely matches your industry.",
      "Review its outcomes, workflows, starter prompts, and safety rules.",
      "Activate one Success Pack as the primary operating pack.",
      "Let LANA route work through the included business team.",
    ],
    tips: ["Only one Success Pack should be primary at a time.", "You can switch packs later.", "Use Memory Packs to enhance, not replace, the Success Pack."],
    related: ["memory-packs", "lana"],
    updated: "2026-10-01",
  },
  {
    id: "memory-packs",
    title: "What Is a Memory Pack?",
    category: "Memory Packs",
    summary: "Memory Packs add deeper knowledge, preferences, guardrails, and team focus.",
    purpose: "Use this after choosing a Success Pack and deciding whether you need extra context.",
    steps: [
      "Choose your active Success Pack first.",
      "Add Memory Packs that match the type of work you do most often.",
      "Review each Memory Pack's team focus, use cases, and guardrails.",
      "Install the Memory Pack as an enhancement layer.",
    ],
    tips: ["Memory Packs are optional.", "Avoid adding packs you do not need.", "Memory Packs do not replace your Success Pack or LANA."],
    related: ["success-packs", "build-my-lux"],
    updated: "2026-10-01",
  },
  {
    id: "lana",
    title: "Meet LANA: Your Lux Agent Coordinator",
    category: "Using Lux Agent",
    summary: "LANA is the executive coordinator installed with every Lux Agent setup.",
    purpose: "Use this to understand what LANA does and how to talk to her.",
    steps: [
      "Tell LANA the goal in plain language.",
      "Give her the important business context before asking for a result.",
      "Let LANA route work to the right specialist agent.",
      "Review drafts, recommendations, and approvals before consequential actions.",
    ],
    tips: ["Ask for a plan before a large task.", "Tell LANA your preferred tone and constraints.", "Use follow-up questions instead of restarting from scratch."],
    related: ["standard-team", "approvals"],
    updated: "2026-10-01",
  },
  {
    id: "standard-team",
    title: "Your Included Professional AI Team",
    category: "Using Lux Agent",
    summary: "Every standard setup includes LANA plus generic business-focused specialist roles.",
    purpose: "Use this to understand the default team before purchasing custom personas.",
    steps: [
      "LANA coordinates Command and planning.",
      "Sales handles leads, follow-up, offers, and customer conversations.",
      "Marketing handles campaigns, positioning, and growth.",
      "Operations handles tasks, schedules, admin flow, and checklists.",
      "Automation & Build handles systems and technical handoffs.",
      "Finance handles budgeting, pricing, and reporting organization.",
      "Research handles market intelligence and sources.",
      "Social & Content handles calendars, posts, and platform formatting.",
    ],
    tips: ["The standard team is designed to work without customization.", "Premium customization is for customers who want unique names, personas, departments, or voice styles."],
    related: ["lana", "premium-team"],
    updated: "2026-10-01",
  },
  {
    id: "premium-team",
    title: "Premium Team Customization",
    category: "Using Lux Agent",
    summary: "Customize departments, names, personas, role details, and voice style when the standard team is not enough.",
    purpose: "Use this when your business needs a custom department or agent instead of the standard team.",
    steps: [
      "Start with the standard team and your Success Pack.",
      "Choose Premium Team Customization in Build My Lux.",
      "Select the departments you want customized.",
      "Describe the role, tone, boundaries, and business needs.",
      "Review the custom Agent Builder configuration before installation.",
    ],
    tips: ["Customization is a premium add-on.", "Keep roles focused and specific.", "Do not add tools or permissions you do not need."],
    related: ["standard-team", "build-my-lux"],
    updated: "2026-10-01",
  },
  {
    id: "installing-lux",
    title: "Install Lux Agent Desktop",
    category: "Installation",
    summary: "What to expect when installing the main Mac or Windows Lux Agent workspace.",
    purpose: "Use this after checkout when your approved installer and signed setup are ready.",
    steps: [
      "Download the approved Lux Agent installer for your computer.",
      "Complete the operating system's normal install approval.",
      "Open Lux Agent and sign in or enter your setup code.",
      "Review the Success Pack, Memory Packs, team, and permissions waiting to install.",
      "Choose Install My Lux and wait for the installation receipt.",
    ],
    tips: ["Do not install files from unofficial sources.", "Keep the setup receipt for troubleshooting.", "Restart only when the installer asks."],
    related: ["updates", "create-usb", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "create-usb",
    title: "Create Your Lux Agent USB",
    category: "USB Travel",
    summary: "Use Lux Agent Desktop to create the portable travel companion on a compatible USB drive.",
    purpose: "Use this when you purchased USB Travel and want to prepare your own drive.",
    steps: [
      "Connect a compatible USB drive with enough free space.",
      "Open the USB Creator from Lux Agent Desktop.",
      "Choose which approved setup, files, and memory should travel.",
      "Review the capacity and compatibility checks.",
      "Choose Create USB and wait for verification to finish.",
    ],
    tips: ["Do not remove the drive during creation.", "Keep sensitive files off the USB unless you need them.", "Reconnect to Desktop later to sync supported changes."],
    related: ["usb-travel", "sync-usb"],
    updated: "2026-10-01",
  },
  {
    id: "usb-travel",
    title: "Using Lux Agent USB While Traveling",
    category: "USB Travel",
    summary: "How to use the portable Lux environment without treating the USB as your main system.",
    purpose: "Use this when working away from your primary Lux Agent Desktop computer.",
    steps: [
      "Connect the Lux Agent USB to a compatible computer.",
      "Launch the portable Lux environment from the approved USB launcher.",
      "Work with the selected agents, files, packs, and travel context available on the drive.",
      "When connected, let Lux sync approved changes back to your main environment.",
      "Safely close Lux before removing the drive.",
    ],
    tips: ["Desktop remains your primary workspace.", "USB carries a selected travel subset.", "Some connected features may require internet access."],
    related: ["create-usb", "sync-usb"],
    updated: "2026-10-01",
  },
  {
    id: "sync-usb",
    title: "Sync USB Changes Back to Desktop",
    category: "USB Travel",
    summary: "Bring approved travel changes back into the main Lux Agent environment.",
    purpose: "Use this after traveling or working from the portable USB environment.",
    steps: [
      "Connect the USB to your main Lux Agent Desktop computer.",
      "Open the sync review.",
      "Review changed files, memory, settings, and queued actions.",
      "Approve only the changes you want merged.",
      "Wait for the sync receipt before removing the drive.",
    ],
    tips: ["Review conflicts instead of blindly overwriting.", "Keep your main Desktop backup current.", "Use the receipt if support needs to trace a sync issue."],
    related: ["create-usb", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "approvals",
    title: "Approvals: When Lux Asks Before Acting",
    category: "Safety & Control",
    summary: "Why Lux pauses before sending, publishing, deleting, purchasing, or making other consequential changes.",
    purpose: "Use this when you see an approval request and want to know what it means.",
    steps: [
      "Read the requested action and the affected account, file, customer, or system.",
      "Review the draft or preview.",
      "Approve only if the result and destination are correct.",
      "Reject or edit the request when anything looks wrong.",
    ],
    tips: ["Approval is a safety feature, not an error.", "Never approve an action you do not understand.", "Ask LANA to explain an approval in plain language."],
    related: ["lana", "updates"],
    updated: "2026-10-01",
  },
  {
    id: "lux-flow",
    title: "Lux Flow: What This Page Is For",
    category: "Product Guides",
    summary: "Lux Flow is where repeatable work becomes a visible workflow.",
    purpose: "Use Lux Flow when a process has clear steps you want to repeat or automate.",
    steps: [
      "Start with the outcome you want.",
      "Add the steps, tools, and handoffs in order.",
      "Place approval gates before consequential actions.",
      "Test the flow with sample data before relying on it.",
      "Review execution status and improve the flow over time.",
    ],
    tips: ["Automate repeatable work, not unclear work.", "Keep approval gates visible.", "Name flows by the outcome they produce."],
    related: ["approvals", "lana"],
    updated: "2026-10-01",
  },
  {
    id: "lux-messages",
    title: "Lux Messages: What This Page Is For",
    category: "Product Guides",
    summary: "Draft, organize, and follow up on customer and business communication.",
    purpose: "Use Lux Messages when you need help writing, tracking, or following up on conversations.",
    steps: [
      "Open the conversation or communication task.",
      "Ask Lux to draft or summarize the message.",
      "Review the recipient, tone, and facts.",
      "Approve the message before sending when approval is required.",
      "Set or review the next follow-up action.",
    ],
    tips: ["Keep outbound messages human.", "Do not send unreviewed sensitive information.", "Use templates for repeated communication."],
    related: ["approvals", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "lux-reader",
    title: "Lux Reader: What This Page Is For",
    category: "Product Guides",
    summary: "Read, summarize, search, and turn documents into useful business context.",
    purpose: "Use Lux Reader for PDFs, reports, policies, guides, books, and other long documents.",
    steps: [
      "Open or import the document.",
      "Ask for a summary or a specific answer.",
      "Jump to the relevant section instead of reading blindly.",
      "Save useful notes, tasks, or business context back into Lux when appropriate.",
    ],
    tips: ["Ask focused questions for better answers.", "Verify important claims against the source document.", "Do not treat a summary as a substitute for professional advice."],
    related: ["lana", "lux-verify"],
    updated: "2026-10-01",
  },
  {
    id: "lux-verify",
    title: "Lux Verify: What This Page Is For",
    category: "Product Guides",
    summary: "Lux Verify separates a claim from the evidence that supports it.",
    purpose: "Use Lux Verify when you need an independent check, evidence, or release confidence.",
    steps: [
      "Choose the item, output, app, or workflow you want checked.",
      "Run the appropriate verification profile.",
      "Review the evidence and any remaining limitations.",
      "Fix failures before treating the result as complete.",
      "Keep the verification receipt with the release or support case.",
    ],
    tips: ["A passed source check is not automatically an installed-app pass.", "Keep evidence with the result.", "Re-run verification after meaningful changes."],
    related: ["updates", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "updates",
    title: "How Lux Agent Updates Work",
    category: "Updates",
    summary: "Lux Agent checks for updates, explains what changed, and lets you choose when to install.",
    purpose: "Use this when the Update button or update notification is highlighted.",
    steps: [
      "Open the update notification or Check for Updates.",
      "Read What's New and review any important behavior changes.",
      "Open the linked update guide or Knowledge Article when available.",
      "Choose Update Now when you are ready.",
      "Watch the progress window and allow Lux to restart when required.",
      "After restart, confirm the new version and review the linked help article.",
    ],
    tips: ["Save important work before updating.", "Do not interrupt an update in progress.", "Use Support if an update fails or gets blocked."],
    related: ["update-troubleshooting", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "update-troubleshooting",
    title: "Troubleshoot a Lux Agent Update",
    category: "Updates",
    summary: "What to do if the updater reports a blocker, manual step, failed check, or restart issue.",
    purpose: "Use this when Update Now does not complete normally.",
    steps: [
      "Read the update window's exact error or blocker.",
      "Close safe blockers only when Lux identifies them.",
      "Retry the update from the same update window.",
      "If Lux gives a manual command, copy only the command shown by the app.",
      "If the problem continues, submit a support case with the version, screenshot, and error message.",
    ],
    tips: ["Do not delete update markers manually unless support instructs you.", "Include the update receipt or screenshot in your case.", "Avoid downloading unofficial replacement installers."],
    related: ["updates", "support-case"],
    updated: "2026-10-01",
  },
  {
    id: "support-case",
    title: "How to Open a Lux Support Case",
    category: "Support",
    summary: "Send the support team the information they need to help quickly.",
    purpose: "Use this when a knowledge article does not solve the problem or you need a team member.",
    steps: [
      "Open Support and choose Submit a Case.",
      "Select the closest category: Bug, How-To, Billing, Access, Integration, or Feature Request.",
      "Describe what you expected, what happened, and what you already tried.",
      "Include screenshots, version information, and receipts when relevant.",
      "Submit the case and keep the case ID for follow-up.",
    ],
    tips: ["One issue per case is easiest to resolve.", "Do not include passwords or API keys.", "Urgent should be reserved for blocking or critical problems."],
    related: ["updates", "update-troubleshooting"],
    updated: "2026-10-01",
  },
  {
    id: "support-priority",
    title: "Support Priorities and Response Expectations",
    category: "Support",
    summary: "How Lux categorizes blocking, high, normal, and low-priority issues.",
    purpose: "Use this when choosing case priority.",
    steps: [
      "Critical: production outage, data loss, or a severe safety issue.",
      "High: blocked from working, billing/access issue, or major failure.",
      "Normal: degraded experience or a problem with a workaround.",
      "Low: cosmetic issue, general question, or feature request.",
    ],
    tips: ["Choosing the correct priority helps the team triage fairly.", "Support may adjust priority after review."],
    related: ["support-case"],
    updated: "2026-10-01",
  },
]

export const KNOWLEDGE_CATEGORIES = [
  "All",
  ...Array.from(new Set(CUSTOMER_KNOWLEDGE.map(article => article.category))).sort(),
]

export function getKnowledgeArticle(id: string) {
  return CUSTOMER_KNOWLEDGE.find(article => article.id === id)
}
