export type LuxProduct = {
  slug: string
  name: string
  short: string
  description: string
  eyebrow: string
  status: "Available" | "Beta" | "Coming Soon"
  icon: string
  image?: string
  hero?: string
  primaryHref: string
  primaryLabel: string
  bullets: string[]
  sections: { title: string; body: string }[]
}

export const LUX_PRODUCTS: LuxProduct[] = [
  {
    slug: "desktop",
    name: "Lux Agent Desktop",
    short: "Your full AI workspace.",
    description: "The main Lux Agent experience for Mac and Windows: LANA, your AI team, files, workflows, voice, tools, approvals, and business context in one private workspace.",
    eyebrow: "Desktop AI Workspace",
    status: "Available",
    icon: "🖥",
    image: "/lux-agent-website/brand/products/lux-agent-desktop-frontback.webp?v=20261001-4",
    hero: "/lux-agent-website/brand/office-executive.png",
    primaryHref: "/download",
    primaryLabel: "Download Lux Agent",
    bullets: ["LANA + your AI team", "Voice and chat", "Files and knowledge", "Workflows and approvals", "Business tools", "Private local-first control"],
    sections: [
      { title: "One place to run the work", body: "Plan, create, organize, research, follow up, and automate from one workspace instead of bouncing between disconnected tools." },
      { title: "A team, not a blank chat box", body: "LANA coordinates specialist agents and keeps the business context in view so work can move from request to result." },
      { title: "Built around your data", body: "Your files, operating rules, packs, and business memory stay under your control with approval gates for sensitive actions." },
    ],
  },
  {
    slug: "usb",
    name: "Lux Agent USB",
    short: "Your AI team on the go.",
    description: "An optional portable companion to Lux Agent Desktop. Build a travel-ready Lux Agent environment on your own compatible USB drive and carry your selected tools, files, context, and agents with you.",
    eyebrow: "Portable Travel Companion",
    status: "Available",
    icon: "🔌",
    image: "/lux-agent-website/brand/products/lux-agent-usb-box.webp?v=20261001-4",
    hero: "/lux-agent-website/brand/office-lounge.png",
    primaryHref: "/products/usb",
    primaryLabel: "Explore Travel USB",
    bullets: ["Portable Lux workspace", "Customer-owned compatible USB", "Selected files and business context", "Offline-capable core experience", "Sync back when connected", "Mac / PC travel workflow"],
    sections: [
      { title: "Desktop at home. Lux on the road.", body: "Lux Agent Desktop remains the full home or office experience. USB is the optional portable companion when you do not want to carry the main computer." },
      { title: "Use your own compatible drive", body: "The standard path is a downloadable portable environment that customers install onto their own sufficiently large compatible USB drive." },
      { title: "Travel light without losing context", body: "Carry selected business memory, files, workflows, and LANA guidance while keeping the full system anchored to the main Lux Agent environment." },
    ],
  },
  {
    slug: "memory-packs",
    name: "Memory Packs",
    short: "Remember more. Do more.",
    description: "Expandable knowledge and context packs that give Lux Agent richer long-term memory for the parts of your work that matter most.",
    eyebrow: "Context + Knowledge",
    status: "Available",
    icon: "🧠",
    image: "/lux-agent-website/brand/products/memory-packs.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-boardroom.png",
    primaryHref: "/memory-packs",
    primaryLabel: "Browse Memory Packs",
    bullets: ["Key context", "Preferences", "Reusable knowledge", "Business memory", "Specialized skills", "Private storage options"],
    sections: [
      { title: "Teach Lux what matters", body: "Memory Packs organize the knowledge, preferences, rules, and reusable context that make your AI team more useful over time." },
      { title: "Keep knowledge modular", body: "Add the memory you need without turning the whole system into one giant unstructured knowledge base." },
      { title: "Move context across your Lux environment", body: "Use memory with Desktop, portable workflows, and supported Lux tools while keeping access boundaries clear." },
    ],
  },
  {
    slug: "success-packs",
    name: "Success Packs",
    short: "Templates. Tools. Training. Real results.",
    description: "Profession-ready operating playbooks with workflows, templates, training, prompts, checklists, and repeatable business systems.",
    eyebrow: "Playbooks + Workflows",
    status: "Available",
    icon: "⭐",
    image: "/lux-agent-website/brand/products/success-packs.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-reception.png",
    primaryHref: "/success-packs",
    primaryLabel: "Browse Success Packs",
    bullets: ["Done-for-you templates", "Step-by-step training", "Industry workflows", "Prompts and checklists", "Launch faster", "Repeatable results"],
    sections: [
      { title: "Start with a proven operating pattern", body: "Success Packs help owners skip the blank-page stage and begin with a usable workflow for their industry or goal." },
      { title: "Built to teach the team", body: "Each pack gives LANA and your AI team a clearer operating playbook for the work you want done." },
      { title: "Customize as you grow", body: "Use the pack as a starting point, then adapt the workflow, templates, and rules to the way your business actually operates." },
    ],
  },
  {
    slug: "flow",
    name: "Lux Flow",
    short: "Build. Connect. Automate.",
    description: "Visual workflow automation for connecting apps, tasks, approvals, and repeatable processes.",
    eyebrow: "Automation",
    status: "Available",
    icon: "⌁",
    image: "/lux-agent-website/brand/products/lux-flow.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-command.png",
    primaryHref: "/products/flow",
    primaryLabel: "Explore Lux Flow",
    bullets: ["Workflow builder", "Connected tools", "Automation steps", "Approval gates", "Reusable recipes", "Execution visibility"],
    sections: [
      { title: "Turn repeated work into a flow", body: "Map the steps once, connect the tools, and let Lux handle the repeatable pieces while keeping human approval where it matters." },
      { title: "See what is happening", body: "Workflows are easier to trust when owners can understand the steps, dependencies, and status instead of sending tasks into a black box." },
      { title: "Connect to the wider Lux ecosystem", body: "Flow is designed to work with Lux Agent, Messages, Reader, Verify, and other supported tools." },
    ],
  },
  {
    slug: "messages",
    name: "Lux Messages",
    short: "Connect. Communicate. Automate.",
    description: "AI-assisted messaging for drafting, organizing conversations, scheduling follow-ups, and turning communication into action.",
    eyebrow: "Communication",
    status: "Available",
    icon: "💬",
    image: "/lux-agent-website/brand/products/lux-messages.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-hallway.png",
    primaryHref: "/products/messages",
    primaryLabel: "Explore Lux Messages",
    bullets: ["Draft and improve messages", "Conversation management", "Follow-up support", "Templates", "AI suggestions", "Owner approvals"],
    sections: [
      { title: "Turn conversations into work", body: "Draft replies, summarize context, identify the next action, and keep follow-ups from disappearing into an inbox." },
      { title: "Stay in control", body: "Use approvals for outbound messages and sensitive communication so AI helps without taking authority away from the owner." },
      { title: "Keep context with the customer", body: "Connect communication to the broader Lux workspace so important relationship context can support future work." },
    ],
  },
  {
    slug: "reader",
    name: "Lux Reader",
    short: "Read. Summarize. Understand faster.",
    description: "An AI document reader for PDFs, guides, reports, books, and business files with summaries, search, notes, and actionable insights.",
    eyebrow: "Knowledge",
    status: "Available",
    icon: "📘",
    image: "/lux-agent-website/brand/products/lux-reader.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-boardroom.png",
    primaryHref: "/products/reader",
    primaryLabel: "Explore Lux Reader",
    bullets: ["PDF and document reading", "AI summaries", "Find anything", "Notes and insights", "Action extraction", "Knowledge handoff"],
    sections: [
      { title: "Get to the useful part faster", body: "Read long documents with AI assistance, jump to the answer you need, and turn dense information into clear next steps." },
      { title: "Keep insight connected to work", body: "Reader is designed to hand useful context back to Lux Agent instead of leaving it trapped inside a separate reading app." },
      { title: "Use it for real business material", body: "Policies, guides, reports, proposals, research, training, and operating documents can all become easier to work with." },
    ],
  },
  {
    slug: "warm-connect",
    name: "Warm Connect",
    short: "People. Opportunities. Real relationships.",
    description: "Relationship and opportunity support for finding the right people, planning outreach, tracking follow-ups, and building stronger professional connections.",
    eyebrow: "Relationships",
    status: "Available",
    icon: "🤝",
    image: "/lux-agent-website/brand/products/warm-connect.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-lounge.png",
    primaryHref: "/products/warm-connect",
    primaryLabel: "Explore Warm Connect",
    bullets: ["Relationship discovery", "AI outreach support", "Follow-up planning", "Opportunity tracking", "Introductions and context", "Network intelligence"],
    sections: [
      { title: "Connect with intention", body: "Use AI to help identify who matters, why the relationship matters, and what a thoughtful next step could look like." },
      { title: "Do not lose the follow-up", body: "Warm Connect helps turn introductions and conversations into organized relationship workflows." },
      { title: "Keep people human", body: "The goal is better preparation and follow-through, not spam. Owners keep final control over outreach." },
    ],
  },
  {
    slug: "verify",
    name: "Lux Verify",
    short: "Audit. Verify. Trust.",
    description: "Verification and evidence tools that help teams inspect outputs, run checks, preserve evidence, and separate a claim from proof.",
    eyebrow: "Trust + Verification",
    status: "Beta",
    icon: "✓",
    image: "/lux-agent-website/brand/products/lux-verify.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-command.png",
    primaryHref: "/products/verify",
    primaryLabel: "Explore Lux Verify",
    bullets: ["Evidence-backed checks", "Application verification", "Risk review", "Audit history", "Independent test lane", "Trust boundaries"],
    sections: [
      { title: "Verification is separate from creation", body: "Lux Verify is designed to inspect work rather than simply trust the same process that produced it." },
      { title: "Preserve the evidence", body: "Checks are more useful when the result, evidence, and remaining limitations can be reviewed later." },
      { title: "Know what passed—and what did not", body: "A source-level success should not silently become an installed-product success. Verify keeps those gates distinct." },
    ],
  },
  {
    slug: "agent-builder",
    name: "Lux Agent Builder",
    short: "Ideas. Agents. Real results.",
    description: "A guided environment for building, configuring, testing, and deploying custom AI agents and workflows for a specific role or business.",
    eyebrow: "Agent Creation",
    status: "Beta",
    icon: "⚙",
    image: "/lux-agent-website/brand/products/agent-builder.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-reception.png",
    primaryHref: "/products/agent-builder",
    primaryLabel: "Explore Agent Builder",
    bullets: ["Agent templates", "Role configuration", "Tool selection", "Workflow design", "Test before launch", "Deployment support"],
    sections: [
      { title: "Turn a role into an agent", body: "Start from the job that needs to be done, then define tools, boundaries, knowledge, and operating rules." },
      { title: "Test before trusting", body: "Agent Builder is designed to pair with verification so new agents can be evaluated before they are treated as production-ready." },
      { title: "Build on the Lux operating model", body: "Custom agents can fit into the same approvals, memory, and workflow structure used across the Lux Agent ecosystem." },
    ],
  },
  {
    slug: "money-suite",
    name: "Lux Money Suite",
    short: "Plan. Track. Understand your money.",
    description: "Business finance organization for invoicing, cash-flow visibility, payments, write-off organization, budgeting, and owner-ready reports.",
    eyebrow: "Business Finance",
    status: "Beta",
    icon: "$",
    image: "/lux-agent-website/brand/products/lux-money-suite.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-executive.png",
    primaryHref: "/products/money-suite",
    primaryLabel: "Explore Money Suite",
    bullets: ["Invoices", "Cash-flow tracking", "Payments", "Budgeting", "Write-off organization", "Business reports"],
    sections: [
      { title: "See the money workflow", body: "Bring common finance tasks into one clearer operating view so the owner can understand what needs attention." },
      { title: "Organize, do not pretend to be a CPA", body: "Money Suite helps organize business information and workflows. Professional tax, accounting, or legal advice remains with qualified professionals." },
      { title: "Connect finance to the rest of the business", body: "Financial visibility is more useful when it can inform planning, reporting, and owner decisions across Lux Agent." },
    ],
  },
  {
    slug: "viewer",
    name: "Lux Agent Viewer",
    short: "Your AI operation at a glance.",
    description: "A dedicated view for seeing agents, devices, workspaces, live status, and system health across the Lux Agent environment.",
    eyebrow: "Monitoring",
    status: "Coming Soon",
    icon: "◉",
    image: "/lux-agent-website/brand/products/lux-agent-viewer-device.webp?v=20261001-3",
    hero: "/lux-agent-website/brand/office-command.png",
    primaryHref: "/products/viewer",
    primaryLabel: "Coming Soon",
    bullets: ["Live status", "Team view", "Device overview", "Workspace visibility", "System health", "Simple monitoring"],
    sections: [
      { title: "See the operation without opening every tool", body: "Viewer is designed as an at-a-glance surface for understanding what is connected, active, healthy, or waiting for attention." },
      { title: "Built for visibility", body: "The goal is a clean monitoring experience for the Lux Agent ecosystem rather than another place where work has to be recreated." },
      { title: "Coming soon", body: "The product is still being prepared for customer release. The site will keep the capability visible without presenting it as generally available today." },
    ],
  },
]

export function getLuxProduct(slug: string) {
  return LUX_PRODUCTS.find(product => product.slug === slug)
}
