insert into public.lux_agent_checkout_catalog (product_key,display_name,kind,active,metadata) values
  ('core_team','Lux Agent Core Business Team','core_team',false,'{"source":"build-my-lux","included_agents":8}'::jsonb),
  ('usb_travel','Lux Agent USB Travel','usb_travel',false,'{"source":"build-my-lux"}'::jsonb),
  ('premium_team','Premium Team Customization','premium_team',false,'{"source":"build-my-lux"}'::jsonb),
  ('success:real_estate','Real Estate Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"real_estate"}'::jsonb),
  ('success:restaurant','Restaurant Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"restaurant"}'::jsonb),
  ('success:doctor_clinic','Doctor / Clinic Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"doctor_clinic"}'::jsonb),
  ('success:electrical_contractor','Electrical Contractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"electrical_contractor"}'::jsonb),
  ('success:creator','Creator Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"creator"}'::jsonb),
  ('success:beauty_salon','Beauty / Salon Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"beauty_salon"}'::jsonb),
  ('success:fitness_coach','Fitness Coach Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"fitness_coach"}'::jsonb),
  ('success:realtor_team','Realtor Team Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"realtor_team"}'::jsonb),
  ('success:insurance_agent','Insurance Agent Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"insurance_agent"}'::jsonb),
  ('success:consultant','Consultant Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"consultant"}'::jsonb),
  ('success:barbershop','Barbershop Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"barbershop"}'::jsonb),
  ('success:auto_repair','Auto Repair Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"auto_repair"}'::jsonb),
  ('success:hvac','HVAC Contractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"hvac"}'::jsonb),
  ('success:plumbing','Plumbing Contractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"plumbing"}'::jsonb),
  ('success:roofing','Roofing Contractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"roofing"}'::jsonb),
  ('success:landscaping','Landscaping Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"landscaping"}'::jsonb),
  ('success:cleaning_service','Cleaning Service Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"cleaning_service"}'::jsonb),
  ('success:mobile_detailing','Mobile Detailing Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"mobile_detailing"}'::jsonb),
  ('success:event_planner','Event Planner Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"event_planner"}'::jsonb),
  ('success:photographer','Photographer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"photographer"}'::jsonb),
  ('success:videographer','Videographer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"videographer"}'::jsonb),
  ('success:podcaster','Podcaster Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"podcaster"}'::jsonb),
  ('success:music_artist','Music Artist Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"music_artist"}'::jsonb),
  ('success:recording_studio','Recording Studio Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"recording_studio"}'::jsonb),
  ('success:dj','DJ Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"dj"}'::jsonb),
  ('success:nonprofit','Nonprofit Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"nonprofit"}'::jsonb),
  ('success:church_ministry','Church / Ministry Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"church_ministry"}'::jsonb),
  ('success:mens_health','Men’s Health Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"mens_health"}'::jsonb),
  ('success:life_coach','Life Coach Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"life_coach"}'::jsonb),
  ('success:business_coach','Business Coach Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"business_coach"}'::jsonb),
  ('success:credit_repair','Credit Repair Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"credit_repair"}'::jsonb),
  ('success:bookkeeping','Bookkeeping Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"bookkeeping"}'::jsonb),
  ('success:tax_preparer','Tax Preparer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"tax_preparer"}'::jsonb),
  ('success:mortgage_broker','Mortgage Broker Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"mortgage_broker"}'::jsonb),
  ('success:property_manager','Property Manager Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"property_manager"}'::jsonb),
  ('success:airbnb_host','Airbnb Host Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"airbnb_host"}'::jsonb),
  ('success:travel_agent','Travel Agent Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"travel_agent"}'::jsonb),
  ('success:food_truck','Food Truck Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"food_truck"}'::jsonb),
  ('success:catering','Catering Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"catering"}'::jsonb),
  ('success:bakery','Bakery Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"bakery"}'::jsonb),
  ('success:coffee_shop','Coffee Shop Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"coffee_shop"}'::jsonb),
  ('success:clothing_brand','Clothing Brand Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"clothing_brand"}'::jsonb),
  ('success:ecommerce','Ecommerce Store Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"ecommerce"}'::jsonb),
  ('success:boutique','Boutique Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"boutique"}'::jsonb),
  ('success:toy_store','Toy Store Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"toy_store"}'::jsonb),
  ('success:pet_groomer','Pet Groomer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"pet_groomer"}'::jsonb),
  ('success:dog_trainer','Dog Trainer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"dog_trainer"}'::jsonb),
  ('success:veterinary','Veterinary Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"veterinary"}'::jsonb),
  ('success:dentist','Dental Practice Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"dentist"}'::jsonb),
  ('success:therapist','Therapist Practice Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"therapist"}'::jsonb),
  ('success:chiropractor','Chiropractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"chiropractor"}'::jsonb),
  ('success:med_spa','Med Spa Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"med_spa"}'::jsonb),
  ('success:lash_artist','Lash Artist Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"lash_artist"}'::jsonb),
  ('success:nail_tech','Nail Tech Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"nail_tech"}'::jsonb),
  ('success:tattoo_artist','Tattoo Artist Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"tattoo_artist"}'::jsonb),
  ('success:personal_trainer','Personal Trainer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"personal_trainer"}'::jsonb),
  ('success:yoga_studio','Yoga Studio Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"yoga_studio"}'::jsonb),
  ('success:dance_studio','Dance Studio Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"dance_studio"}'::jsonb),
  ('success:martial_arts','Martial Arts Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"martial_arts"}'::jsonb),
  ('success:tutor','Tutoring Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"tutor"}'::jsonb),
  ('success:daycare','Daycare Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"daycare"}'::jsonb),
  ('success:private_school','Private School Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"private_school"}'::jsonb),
  ('success:course_creator','Course Creator Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"course_creator"}'::jsonb),
  ('success:author','Author Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"author"}'::jsonb),
  ('success:speaker','Public Speaker Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"speaker"}'::jsonb),
  ('success:law_firm','Law Firm Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"law_firm"}'::jsonb),
  ('success:accountant','Accounting Firm Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"accountant"}'::jsonb),
  ('success:architect','Architect Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"architect"}'::jsonb),
  ('success:interior_designer','Interior Designer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"interior_designer"}'::jsonb),
  ('success:construction','Construction Company Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"construction"}'::jsonb),
  ('success:handyman','Handyman Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"handyman"}'::jsonb),
  ('success:pest_control','Pest Control Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"pest_control"}'::jsonb),
  ('success:security_company','Security Company Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"security_company"}'::jsonb),
  ('success:moving_company','Moving Company Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"moving_company"}'::jsonb),
  ('success:logistics','Logistics Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"logistics"}'::jsonb),
  ('success:trucking','Trucking Business Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"trucking"}'::jsonb),
  ('success:car_rental','Car Rental Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"car_rental"}'::jsonb),
  ('success:rideshare','Rideshare Driver Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"rideshare"}'::jsonb),
  ('success:delivery_service','Delivery Service Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"delivery_service"}'::jsonb),
  ('success:warehouse','Warehouse Ops Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"warehouse"}'::jsonb),
  ('success:manufacturing','Manufacturing Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"manufacturing"}'::jsonb),
  ('success:janitorial_contract','Janitorial Contracts Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"janitorial_contract"}'::jsonb),
  ('success:government_contractor','Government Contractor Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"government_contractor"}'::jsonb),
  ('success:grant_writer','Grant Writer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"grant_writer"}'::jsonb),
  ('success:community_org','Community Organization Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"community_org"}'::jsonb),
  ('success:youth_program','Youth Program Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"youth_program"}'::jsonb),
  ('success:senior_care','Senior Care Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"senior_care"}'::jsonb),
  ('success:home_health','Home Health Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"home_health"}'::jsonb),
  ('success:wellness_clinic','Wellness Clinic Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"wellness_clinic"}'::jsonb),
  ('success:bar_lounge','Bar / Lounge Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"bar_lounge"}'::jsonb),
  ('success:nightclub','Nightclub Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"nightclub"}'::jsonb),
  ('success:event_venue','Event Venue Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"event_venue"}'::jsonb),
  ('success:sports_trainer','Sports Trainer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"sports_trainer"}'::jsonb),
  ('success:sports_team','Sports Team Ops Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"sports_team"}'::jsonb),
  ('success:artist_manager','Artist Manager Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"artist_manager"}'::jsonb),
  ('success:label_manager','Record Label Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"label_manager"}'::jsonb),
  ('success:film_producer','Film Producer Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"film_producer"}'::jsonb),
  ('success:influencer_agency','Influencer Agency Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"influencer_agency"}'::jsonb),
  ('success:marketing_agency','Marketing Agency Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"marketing_agency"}'::jsonb),
  ('success:seo_agency','SEO Agency Success Pack','success_pack',false,'{"source":"build-my-lux","source_id":"seo_agency"}'::jsonb),
  ('memory:mp001_founder_identity_and_voice','Founder Identity & Voice Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP001_founder_identity_and_voice"}'::jsonb),
  ('memory:mp002_daily_discipline_os','Daily Discipline OS Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP002_daily_discipline_os"}'::jsonb),
  ('memory:mp003_confidence_builder','Confidence Builder Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP003_confidence_builder"}'::jsonb),
  ('memory:mp004_negotiation_street_smarts','Negotiation Street Smarts Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP004_negotiation_street_smarts"}'::jsonb),
  ('memory:mp005_public_speaking_and_pitching','Public Speaking & Pitching Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP005_public_speaking_and_pitching"}'::jsonb),
  ('memory:mp006_emotional_resilience','Emotional Resilience Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP006_emotional_resilience"}'::jsonb),
  ('memory:mp007_leadership_presence','Leadership Presence Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP007_leadership_presence"}'::jsonb),
  ('memory:mp008_time_blocking_and_focus','Time Blocking & Focus Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP008_time_blocking_and_focus"}'::jsonb),
  ('memory:mp009_decision_maker_framework','Decision Maker Framework Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP009_decision_maker_framework"}'::jsonb),
  ('memory:mp010_faith_purpose_and_values','Faith, Purpose & Values Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP010_faith_purpose_and_values"}'::jsonb),
  ('memory:mp011_consultative_selling','Consultative Selling Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP011_consultative_selling"}'::jsonb),
  ('memory:mp012_cold_outreach_that_feels_human','Cold Outreach That Feels Human Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP012_cold_outreach_that_feels_human"}'::jsonb),
  ('memory:mp013_follow_up_machine','Follow-Up Machine Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP013_follow_up_machine"}'::jsonb),
  ('memory:mp014_objection_handling','Objection Handling Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP014_objection_handling"}'::jsonb),
  ('memory:mp015_offer_design','Offer Design Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP015_offer_design"}'::jsonb),
  ('memory:mp016_proposal_writing','Proposal Writing Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP016_proposal_writing"}'::jsonb),
  ('memory:mp017_pricing_psychology','Pricing Psychology Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP017_pricing_psychology"}'::jsonb),
  ('memory:mp018_client_retention','Client Retention Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP018_client_retention"}'::jsonb),
  ('memory:mp019_referral_flywheel','Referral Flywheel Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP019_referral_flywheel"}'::jsonb),
  ('memory:mp020_local_networking','Local Networking Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP020_local_networking"}'::jsonb),
  ('memory:mp021_brand_voice_engine','Brand Voice Engine Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP021_brand_voice_engine"}'::jsonb),
  ('memory:mp022_storytelling_for_business','Storytelling for Business Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP022_storytelling_for_business"}'::jsonb),
  ('memory:mp023_social_hook_library','Social Hook Library Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP023_social_hook_library"}'::jsonb),
  ('memory:mp024_content_calendar_rhythm','Content Calendar Rhythm Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP024_content_calendar_rhythm"}'::jsonb),
  ('memory:mp025_short_video_script_lab','Short Video Script Lab Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP025_short_video_script_lab"}'::jsonb),
  ('memory:mp026_email_marketing_basics','Email Marketing Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP026_email_marketing_basics"}'::jsonb),
  ('memory:mp027_campaign_planner','Campaign Planner Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP027_campaign_planner"}'::jsonb),
  ('memory:mp028_community_building','Community Building Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP028_community_building"}'::jsonb),
  ('memory:mp029_creator_economy_strategy','Creator Economy Strategy Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP029_creator_economy_strategy"}'::jsonb),
  ('memory:mp030_pr_and_media_angle_finder','PR & Media Angle Finder Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP030_pr_and_media_angle_finder"}'::jsonb),
  ('memory:mp031_sop_builder','SOP Builder Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP031_sop_builder"}'::jsonb),
  ('memory:mp032_calendar_command','Calendar Command Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP032_calendar_command"}'::jsonb),
  ('memory:mp033_task_triage','Task Triage Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP033_task_triage"}'::jsonb),
  ('memory:mp034_inbox_and_message_cleanup','Inbox & Message Cleanup Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP034_inbox_and_message_cleanup"}'::jsonb),
  ('memory:mp035_customer_service_playbook','Customer Service Playbook Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP035_customer_service_playbook"}'::jsonb),
  ('memory:mp036_project_management_basics','Project Management Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP036_project_management_basics"}'::jsonb),
  ('memory:mp037_vendor_management','Vendor Management Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP037_vendor_management"}'::jsonb),
  ('memory:mp038_quality_control','Quality Control Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP038_quality_control"}'::jsonb),
  ('memory:mp039_hiring_and_onboarding','Hiring & Onboarding Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP039_hiring_and_onboarding"}'::jsonb),
  ('memory:mp040_light_compliance_and_records','Light Compliance & Records Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP040_light_compliance_and_records"}'::jsonb),
  ('memory:mp041_cash_flow_clarity','Cash Flow Clarity Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP041_cash_flow_clarity"}'::jsonb),
  ('memory:mp042_budget_discipline','Budget Discipline Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP042_budget_discipline"}'::jsonb),
  ('memory:mp043_tax_document_organizer','Tax Document Organizer Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP043_tax_document_organizer"}'::jsonb),
  ('memory:mp044_write_off_thinking','Write-Off Thinking Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP044_write_off_thinking"}'::jsonb),
  ('memory:mp045_profit_margin_coach','Profit Margin Coach Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP045_profit_margin_coach"}'::jsonb),
  ('memory:mp046_bookkeeping_basics','Bookkeeping Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP046_bookkeeping_basics"}'::jsonb),
  ('memory:mp047_grant_readiness','Grant Readiness Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP047_grant_readiness"}'::jsonb),
  ('memory:mp048_funding_pitch_prep','Funding Pitch Prep Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP048_funding_pitch_prep"}'::jsonb),
  ('memory:mp049_subscription_revenue_model','Subscription Revenue Model Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP049_subscription_revenue_model"}'::jsonb),
  ('memory:mp050_roi_and_value_calculator','ROI & Value Calculator Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP050_roi_and_value_calculator"}'::jsonb),
  ('memory:mp051_market_research','Market Research Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP051_market_research"}'::jsonb),
  ('memory:mp052_competitor_analysis','Competitor Analysis Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP052_competitor_analysis"}'::jsonb),
  ('memory:mp053_trend_watch','Trend Watch Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP053_trend_watch"}'::jsonb),
  ('memory:mp054_local_opportunity_scout','Local Opportunity Scout Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP054_local_opportunity_scout"}'::jsonb),
  ('memory:mp055_grant_and_funding_scout','Grant & Funding Scout Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP055_grant_and_funding_scout"}'::jsonb),
  ('memory:mp056_vendor_and_tool_sourcing','Vendor & Tool Sourcing Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP056_vendor_and_tool_sourcing"}'::jsonb),
  ('memory:mp057_customer_interview_framework','Customer Interview Framework Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP057_customer_interview_framework"}'::jsonb),
  ('memory:mp058_data_literacy','Data Literacy Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP058_data_literacy"}'::jsonb),
  ('memory:mp059_ai_tools_watchtower','AI Tools Watchtower Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP059_ai_tools_watchtower"}'::jsonb),
  ('memory:mp060_citation_and_source_hygiene','Citation & Source Hygiene Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP060_citation_and_source_hygiene"}'::jsonb),
  ('memory:mp061_website_briefing','Website Briefing Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP061_website_briefing"}'::jsonb),
  ('memory:mp062_no_code_app_planner','No-Code App Planner Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP062_no_code_app_planner"}'::jsonb),
  ('memory:mp063_api_basics','API Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP063_api_basics"}'::jsonb),
  ('memory:mp064_automation_workflow_design','Automation Workflow Design Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP064_automation_workflow_design"}'::jsonb),
  ('memory:mp065_local_ai_setup_thinking','Local AI Setup Thinking Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP065_local_ai_setup_thinking"}'::jsonb),
  ('memory:mp066_prompt_engineering','Prompt Engineering Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP066_prompt_engineering"}'::jsonb),
  ('memory:mp067_qa_testing_mindset','QA Testing Mindset Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP067_qa_testing_mindset"}'::jsonb),
  ('memory:mp068_security_and_privacy_basics','Security & Privacy Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP068_security_and_privacy_basics"}'::jsonb),
  ('memory:mp069_data_schema_planner','Data Schema Planner Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP069_data_schema_planner"}'::jsonb),
  ('memory:mp070_deployment_readiness','Deployment Readiness Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP070_deployment_readiness"}'::jsonb),
  ('memory:mp071_stress_management','Stress Management Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP071_stress_management"}'::jsonb),
  ('memory:mp072_morning_routine','Morning Routine Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP072_morning_routine"}'::jsonb),
  ('memory:mp073_sleep_and_energy','Sleep & Energy Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP073_sleep_and_energy"}'::jsonb),
  ('memory:mp074_nutrition_basics','Nutrition Basics Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP074_nutrition_basics"}'::jsonb),
  ('memory:mp075_gym_discipline','Gym Discipline Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP075_gym_discipline"}'::jsonb),
  ('memory:mp076_family_and_relationship_balance','Family & Relationship Balance Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP076_family_and_relationship_balance"}'::jsonb),
  ('memory:mp077_boundary_setting','Boundary Setting Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP077_boundary_setting"}'::jsonb),
  ('memory:mp078_travel_planning','Travel Planning Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP078_travel_planning"}'::jsonb),
  ('memory:mp079_home_organization','Home Organization Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP079_home_organization"}'::jsonb),
  ('memory:mp080_personal_finance_discipline','Personal Finance Discipline Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP080_personal_finance_discipline"}'::jsonb),
  ('memory:mp081_urban_vibes_brand_sense','Urban Vibes Brand Sense Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP081_urban_vibes_brand_sense"}'::jsonb),
  ('memory:mp082_gospel_and_hip_hop_inspiration','Gospel & Hip-Hop Inspiration Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP082_gospel_and_hip_hop_inspiration"}'::jsonb),
  ('memory:mp083_black_business_excellence','Black Business Excellence Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP083_black_business_excellence"}'::jsonb),
  ('memory:mp084_minority_opportunity_lens','Minority Opportunity Lens Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP084_minority_opportunity_lens"}'::jsonb),
  ('memory:mp085_church_and_community_connector','Church & Community Connector Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP085_church_and_community_connector"}'::jsonb),
  ('memory:mp086_event_host_energy','Event Host Energy Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP086_event_host_energy"}'::jsonb),
  ('memory:mp087_music_studio_culture','Music Studio Culture Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP087_music_studio_culture"}'::jsonb),
  ('memory:mp088_sports_fan_engagement','Sports Fan Engagement Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP088_sports_fan_engagement"}'::jsonb),
  ('memory:mp089_sneaker_and_streetwear_culture','Sneaker & Streetwear Culture Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP089_sneaker_and_streetwear_culture"}'::jsonb),
  ('memory:mp090_portland_local_context','Portland Local Context Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP090_portland_local_context"}'::jsonb),
  ('memory:mp091_hospitality_operator','Hospitality Operator Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP091_hospitality_operator"}'::jsonb),
  ('memory:mp092_field_services_operator','Field Services Operator Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP092_field_services_operator"}'::jsonb),
  ('memory:mp093_healthcare_office_ops','Healthcare Office Ops Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP093_healthcare_office_ops"}'::jsonb),
  ('memory:mp094_real_estate_operator','Real Estate Operator Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP094_real_estate_operator"}'::jsonb),
  ('memory:mp095_entertainment_business','Entertainment Business Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP095_entertainment_business"}'::jsonb),
  ('memory:mp096_education_business','Education Business Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP096_education_business"}'::jsonb),
  ('memory:mp097_beauty_business','Beauty Business Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP097_beauty_business"}'::jsonb),
  ('memory:mp098_nonprofit_and_impact','Nonprofit & Impact Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP098_nonprofit_and_impact"}'::jsonb),
  ('memory:mp099_agency_operator','Agency Operator Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP099_agency_operator"}'::jsonb),
  ('memory:mp100_logistics_and_operations','Logistics & Operations Memory Pack','memory_pack',false,'{"source":"build-my-lux","source_id":"MP100_logistics_and_operations"}'::jsonb)
on conflict (product_key) do nothing;
